### ISSUE TITLE
[Enhancement]: About section for this repo

### ISSUE THREAD

**Issue by chaitanyakatore** [surrealdb/surrealml#1]
- I think we should write something in about section of this repository
- it will give some quick readability to this repo

**Comment by maxwellflitton** [comment]
Hey @chaitanyakatore sorry about the extremely delayed response. I was working to get all the moving parts working together here and in the SurrealDB server. This also included the surrealml core which is its own stand alone rust crate. I now have a readme in the repo. Is it clear enough or do you want more things added?
