### ISSUE TITLE
[ERROR]: `sklearn` example doesn't run 

### ISSUE THREAD

**Issue by AyushChothe** [surrealdb/surrealml#14]
```py
import numpy as np
from sklearn.ensemble import RandomForestClassifier

from surrealml import SurMlFile

num_classes = 2
X = np.random.rand(100, 28)
y = np.random.randint(num_classes, size=100)

skl_model = RandomForestClassifier(n_estimators=10, max_depth=10)
skl_model.fit(X, y)

test_file = SurMlFile(
    model=skl_model,
    name="random forrest classifier",
    inputs=X,
    sklearn=True,
)
test_file.save("./test_forrest.surml")

# load model and execute a calculation
random_floats = list(np.random.rand(28))
test_load = SurMlFile.load("./test_forrest.surml")

```

```bash
Model saved with digest: 747dc97cf71db25ea44fe440cdd726d46651fbd5
/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/torch/onnx/utils.py:825: UserWarning: no signature found for <torch.ScriptMethod object at 0x297134bf0>, skipping _decide_input_format
  warnings.warn(f"{e}, skipping _decide_input_format")
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/Users/ayush/Projects/ML/surrealml_demo/sklean.py", line 13, in <module>
    test_file = SurMlFile(
                ^^^^^^^^^^
  File "/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/surrealml/surml_file.py", line 35, in __init__
    self.file_id = self._cache_model()
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/surrealml/surml_file.py", line 59, in _cache_model
    torch.onnx.export(traced_script_module, self.inputs, file_path)
  File "/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayush/miniconda3/envs/surml/lib/python3.11/site-packages/torch/onnx/utils.py", line 956, in _create_jit_graph
    flattened_args = tuple(torch.jit._flatten(tuple(args))[0])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: numpy.ndarray
```

**Comment by YanshiAI** [comment]
hey! It seems you’ve provided a numpy ndarray, which is not supported. You can convert a numpy ndarray to a PyTorch tensor .

**Comment by maxwellflitton** [comment]
Hey @AyushChothe thanks for the report. I've looked into it and you're right the sklearn doesn't seem to be working now. I've inspected it and the sklearn model before the `torch.onnx.export` which gives the following:
```python
RecursiveScriptModule(
  original_name=Executor
  (_operators): RecursiveScriptModule(
    original_name=ModuleList
    (0): RecursiveScriptModule(
      original_name=PerfectTreeTraversalDecisionTreeImpl
      (nodes): RecursiveScriptModule(original_name=ParameterList)
      (biases): RecursiveScriptModule(original_name=ParameterList)
    )
  )
)
<class 'torch.jit._script.RecursiveScriptModule'>
```
Which is a traced `torch` model. I'm looking into the issue now.

**Comment by AyushChothe** [comment]
Hey @maxwellflitton, any updates on this?

**Comment by maxwellflitton** [comment]
@AyushChothe Yes, I have gotten the ONNX export mechanism into a testing harness, and I've got it working in isolation, I am now working on integrating this into the package. This will include separating the torch from the sklearn so you don't need both installed. Will hopefully be done in the next couple of days.

**Comment by maxwellflitton** [comment]
@AyushChothe just updating you. The integration of the new `sklearn` conversion to `ONNX` broke the `ONNX`, so I have now experimented with `ort` new `2.0` `alpha` and it's working:

<img width="908" alt="Screenshot 2024-01-18 at 16 36 44" src="https://github.com/surrealdb/surrealml/assets/17654010/3e68e332-ee50-46cb-af9f-adf88dbb79c8">

So I am going to have to work in integrating this new `2.0 alpha` version of `ort` into the core part of the ML. Then the updated version of sklearn to onnx conversion will also work. Sorry for the delay, there seems to be mega changes in the underlying ONNX engine for rust.

**Comment by AyushChothe** [comment]
> @AyushChothe just updating you. The integration of the new `sklearn` conversion to `ONNX` broke the `ONNX`, so I have now experimented with `ort` new `2.0` `alpha` and it's working:
> 
> <img width="908" alt="Screenshot 2024-01-18 at 16 36 44" src="https://github.com/surrealdb/surrealml/assets/17654010/3e68e332-ee50-46cb-af9f-adf88dbb79c8">
> 
> So I am going to have to work in integrating this new `2.0 alpha` version of `ort` into the core part of the ML. Then the updated version of sklearn to onnx conversion will also work. Sorry for the delay, there seems to be mega changes in the underlying ONNX engine for rust.

@maxwellflitton Thanks for the update. Looking forward to test it.

**Comment by maxwellflitton** [comment]
@AyushChothe just to give you an update on what's going on. I have now implemented end-to-end testing and more unit testing. As you can see in the new pull request I have created model templates for sklearn and torch in the following directory:

https://github.com/surrealdb/surrealml/tree/python-engine-adapters/surrealml/model_templates

Right now it's just linear regression as I wanted to ensure that the saving and running is working as expected. The models are then trained and cached in the following script:

https://github.com/surrealdb/surrealml/blob/43ffad727c7b71ce1f828f494015fa561b6fe3b7/tests/scripts/build_assets.py#L95

The training and exporting of the stashed models rely on the `surml` object as we can see here:

https://github.com/surrealdb/surrealml/blob/python-engine-adapters/surrealml/model_templates/sklearn/sklearn_linear.py

and these stashed models are now tested in the core rust library for loading the models as seen here:

https://github.com/surrealdb/surrealml/blob/43ffad727c7b71ce1f828f494015fa561b6fe3b7/modules/core/src/execution/compute.rs#L155

We also test the transfer for these models over a HTTP network with the following code:

https://github.com/surrealdb/surrealml/blob/43ffad727c7b71ce1f828f494015fa561b6fe3b7/src/transport.rs#L74

Everything is now passing integration tests. The pull request spans over 90 files and nearly 1,200 lines of code but I wanted to ensure that the whole process is fully tested and locked down to prevent frustration and blocking happening due to errors. I am now working on the documentation as the interface has changed slightly but it will be hopefully live soon. Thanks for being patient.

**Comment by AyushChothe** [comment]
> @AyushChothe just to give you an update on what's going on. I have now implemented end-to-end testing and more unit testing. As you can see in the new pull request I have created model templates for sklearn and torch in the following directory:
> 
> https://github.com/surrealdb/surrealml/tree/python-engine-adapters/surrealml/model_templates
> 
> Right now it's just linear regression as I wanted to ensure that the saving and running is working as expected. The models are then trained and cached in the following script:
> 
> https://github.com/surrealdb/surrealml/blob/43ffad727c7b71ce1f828f494015fa561b6fe3b7/tests/scripts/build_assets.py#L95
> 
> The training and exporting of the stashed models rely on the `surml` object as we can see here:
> 
> https://github.com/surrealdb/surrealml/blob/python-engine-adapters/surrealml/model_templates/sklearn/sklearn_linear.py
> 
> and these stashed models are now tested in the core rust library for loading the models as seen here:
> 
> https://github.com/surrealdb/surrealml/blob/43ffad727c7b71ce1f828f494015fa561b6fe3b7/modules/core/src/execution/compute.rs#L155
> 
> We also test the transfer for these models over a HTTP network with the following code:
> 
> https://github.com/surrealdb/surrealml/blob/43ffad727c7b71ce1f828f494015fa561b6fe3b7/src/transport.rs#L74
> 
> Everything is now passing integration tests. The pull request spans over 90 files and nearly 1,200 lines of code but I wanted to ensure that the whole process is fully tested and locked down to prevent frustration and blocking happening due to errors. I am now working on the documentation as the interface has changed slightly but it will be hopefully live soon. Thanks for being patient.

Thanks for the update, I was following the PR from few days. 🫡

**Comment by maxwellflitton** [comment]
@AyushChothe it's now passing and I've pushed it but I have only tested it using linear regression models for sklearn and torch. I will add more templates as time goes on so we can test them and they should just work. Let me know if the new interface works for you.
