### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jmadotgg** [surrealdb/surrealml#6]
I tried installing SurrealML using
`pip install git+https://github.com/surrealdb/surrealml` in Python 3.11.6. 

Unfortunately I am running into this error:
```error: couldn't read modules/utils/src/execution/../../onnx_driver/target/debug/libonnxruntime.dylib: No such file or directory (os error 2)
       --> modules/utils/src/execution/onnx_environment.rs:9:39
        |
      9 | pub static LIB_BYTES: &'static [u8] = include_bytes!("../../onnx_driver/target/debug/libonnxruntime.dylib");
        |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

      error: could not compile `surrealml-core` (lib) due to 1 previous error

```
My default toolchain is _nightly-x86_64-apple-darwin_ (1.77).

I also installed `onnxruntime` via pip and homebrew just in case.

Please tell me what I'm missing. Are there any installation instructions?

**Comment by adityak74** [comment]
@jmadotgg It worked for me in python `3.11.0`. Used the same command `pip install git+https://github.com/surrealdb/surrealml`.

**Comment by jmadotgg** [comment]
Yes indeed, it works after @tobiemh fix.
